/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slabfr;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;

public class StartTest {
    @Test public void testStartHasLogger() throws SecurityException, IOException {
        Start classUnderTest = new Start();
        assertNotNull("Start should have a logger", classUnderTest.logger);
    }
    
    @Test public void testStartHasFileHandler() throws SecurityException, IOException {
        Start classUnderTest = new Start();
        assertNotNull("Start should have a file handler", classUnderTest.fH);
    }
}
