name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build with gradle wrapper
        run: ./gradlew build
      - name: upload distribution
        uses: actions/upload-artifact@v3
        with:
          name: slabr.zip zipped
          path: build/distributions/slabfr.zip
        